### ISSUE TITLE
2024 University of Waterloo Fall Kickoff Race

### ISSUE THREAD

**Issue by ATATC** [ProjectNeura/LEADS#436]
@ProjectNeura/vec
Hi all,
Data and feedback from the 2024 University of Waterloo Fall Kickoff Race shall be posted here.

**Comment by ATATC** [comment]
[main.csv](https://github.com/user-attachments/files/17267096/main.csv)

**Comment by ATATC** [comment]
@aforti86 Do we have the table of lap times?

**Comment by ATATC** [comment]
![image](https://github.com/user-attachments/assets/b9e100b7-c90a-4dd8-8e2b-66dd45c5dfc6)

**Comment by ATATC** [comment]
```yaml
dataset: "data/main.csv"

jobs:
  - name: Task 1
    uses: bake
  - name: Task 2
    uses: process
    with:
      vehicle_hit_box: 2  # default: 3
      min_lap_time: 50  # default: 30 (seconds)
  - name: Draw Lap 16
    uses: draw-lap
    with:
      lap_index: 15
  - name: Draw Comparison of Laps
    uses: draw-comparison-of-laps
    with:
      width: 0.3  # default: 0.3
```
